# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orchestrator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x0corchestrator\"\x1c\n\x03\x43SR\x12\x15\n\rdevice_pubkey\x18\x01 \x01(\x0c\"\x1a\n\x0b\x43\x65rtificate\x12\x0b\n\x03pem\x18\x01 \x01(\x0c\"\x16\n\x08\x44\x65viceId\x12\n\n\x02id\x18\x01 \x01(\x0c\"\x9f\x01\n\rRoundMetadata\x12\x10\n\x08round_id\x18\x01 \x01(\x04\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x13\n\x0b\x65psilon_max\x18\x03 \x01(\x01\x12\x12\n\nupload_uri\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x13\n\x0bnum_updates\x18\x06 \x01(\r\x12\x18\n\x10\x61ggregation_mode\x18\x07 \x01(\t\"\x9e\x01\n\x07Receipt\x12\x11\n\tdevice_id\x18\x01 \x01(\x0c\x12\x10\n\x08round_id\x18\x02 \x01(\x04\x12\x14\n\x0cpayload_hash\x18\x03 \x01(\x0c\x12\x15\n\repsilon_spent\x18\x04 \x01(\x01\x12\x11\n\tsignature\x18\x05 \x01(\x0c\x12\x0f\n\x07\x65nc_uri\x18\x06 \x01(\t\x12\x0e\n\x06scheme\x18\x07 \x01(\t\x12\r\n\x05nonce\x18\x08 \x01(\t\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xca\x01\n\x0cOrchestrator\x12>\n\x0eRegisterDevice\x12\x11.orchestrator.CSR\x1a\x19.orchestrator.Certificate\x12?\n\x08GetRound\x12\x16.orchestrator.DeviceId\x1a\x1b.orchestrator.RoundMetadata\x12\x39\n\rSubmitReceipt\x12\x15.orchestrator.Receipt\x1a\x11.orchestrator.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CSR']._serialized_start=36
  _globals['_CSR']._serialized_end=64
  _globals['_CERTIFICATE']._serialized_start=66
  _globals['_CERTIFICATE']._serialized_end=92
  _globals['_DEVICEID']._serialized_start=94
  _globals['_DEVICEID']._serialized_end=116
  _globals['_ROUNDMETADATA']._serialized_start=119
  _globals['_ROUNDMETADATA']._serialized_end=278
  _globals['_RECEIPT']._serialized_start=281
  _globals['_RECEIPT']._serialized_end=439
  _globals['_ACK']._serialized_start=441
  _globals['_ACK']._serialized_end=458
  _globals['_ORCHESTRATOR']._serialized_start=461
  _globals['_ORCHESTRATOR']._serialized_end=663
# @@protoc_insertion_point(module_scope)
